# Generated by Django 3.1.7 on 2021-02-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0002_auto_20210222_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tagged_polls', to='pollster.Topic'),
        ),
    ]
