# Generated by Django 3.1.7 on 2021-02-27 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0003_auto_20210223_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pollster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
